# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modelsim/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.cache/wt [current_project]
set_property parent.project_path C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/sources_1/new/latch.v
  C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/sources_1/new/div.v
  C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/sources_1/new/counter_10.v
  C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/sources_1/new/control.v
  C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/sources_1/new/IP_seg_disp.v
  C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/sources_1/new/freDetect.v
}
read_xdc C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/constrs_1/new/test.xdc
set_property used_in_implementation false [get_files C:/Users/xushu/Desktop/FPGa/project/freDetect_2/freDetect_2.srcs/constrs_1/new/test.xdc]

synth_design -top freDetect -part xc7a100tcsg324-1
write_checkpoint -noxdef freDetect.dcp
catch { report_utilization -file freDetect_utilization_synth.rpt -pb freDetect_utilization_synth.pb }
